# .sync.yml
---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-strings'
        git: 'https://github.com/puppetlabs/puppet-strings.git'
        ref: 'master'
      - gem: 'webmock'
      - gem: 'puppet-resource_api'
      - gem: 'algosec-sdk'
        version: '~> 1.2.0'
      # required for internal pipelines
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

Rakefile:
#  changelog_user: 'puppetlabs'
  requires:
  - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
  - "require 'webmock/rspec'"
.travis.yml:
  simplecov: true
.gitignore:
  paths:
  - spec/fixtures/acceptance-credentials.conf
  - spec/fixtures/acceptance-device.conf
.pdkignore:
  paths:
  - spec/fixtures/acceptance-credentials.conf
  - spec/fixtures/acceptance-device.conf
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true